import type { Product } from './types';

const u = (id: string, w = 1200) =>
  `https://images.unsplash.com/${id}?w=${w}&q=85&auto=format&fit=crop`;

export const PRODUCTS: Product[] = [
  {
    id: 'p-001',
    slug: 'veste-cargo-beige-ilu',
    name: 'Veste Cargo Beige',
    shortDescription: 'Coupe oversize, coton lavé',
    description:
      "Une pièce signature ILU. Coton lavé doux au toucher, poches utilitaires, ourlets renforcés. Inspirée de l'esthétique workwear contemporaine, elle s'associe aussi bien à un denim brut qu'à un pantalon ample.",
    priceUSD: 89,
    oldPriceUSD: 112,
    category: 'mode',
    subcategory: 'Vestes & Manteaux',
    tags: ['nouveauté', 'workwear', 'unisexe'],
    status: 'featured',
    stock: 12,
    rating: 4.8,
    reviewCount: 142,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Beige', hex: '#E8DDD0' },
      { name: 'Terracotta', hex: '#C8573A' },
      { name: 'Olive', hex: '#6B6B3A' },
    ],
    images: [
      u('photo-1591047139829-d91aecb6caea'),
      u('photo-1551028719-00167b16eac5'),
      u('photo-1544022613-e87ca75a784a'),
    ],
    badge: 'featured',
  },
  {
    id: 'p-002',
    slug: 'sneakers-blanc-minimal',
    name: 'Sneakers Blanc Minimal',
    shortDescription: 'Cuir grainé, semelle vulcanisée',
    description:
      'Sneakers minimalistes en cuir grainé blanc cassé. Une silhouette épurée pensée pour durer, semelle vulcanisée confortable, lacets cirés tissés à la main.',
    priceUSD: 49,
    category: 'mode',
    subcategory: 'Chaussures',
    tags: ['classique', 'cuir'],
    status: 'featured',
    stock: 24,
    rating: 4.6,
    reviewCount: 89,
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: [
      { name: 'Blanc cassé', hex: '#F5EFE6' },
      { name: 'Noir', hex: '#1C1410' },
    ],
    images: [
      u('photo-1542291026-7eec264c27ff'),
      u('photo-1525966222134-fcfa99b8ae77'),
    ],
    badge: 'hot',
  },
  {
    id: 'p-003',
    slug: 'sac-cabas-cuir-terra',
    name: 'Cabas Cuir Terracotta',
    shortDescription: 'Cuir pleine fleur, finition à la main',
    description:
      'Cabas en cuir pleine fleur teinté à la main dans nos ateliers. Doublure coton, poche zippée intérieure, anses longues. Une pièce qui se patine magnifiquement avec le temps.',
    priceUSD: 145,
    category: 'mode',
    subcategory: 'Sacs & Maroquinerie',
    tags: ['cuir', 'artisanal'],
    status: 'featured',
    stock: 6,
    rating: 4.9,
    reviewCount: 56,
    colors: [
      { name: 'Terracotta', hex: '#C8573A' },
      { name: 'Cognac', hex: '#9B5A28' },
      { name: 'Noir', hex: '#1C1410' },
    ],
    images: [
      u('photo-1548036328-c9fa89d128fa'),
      u('photo-1590874103328-eac38a683ce7'),
    ],
    badge: 'new',
  },
  {
    id: 'p-004',
    slug: 'manteau-laine-camel',
    name: 'Manteau Laine Camel',
    shortDescription: 'Laine recyclée, coupe droite',
    description:
      'Manteau long en laine recyclée, coupe droite intemporelle. Doublure satin, deux poches passepoilées, bouton corne véritable. Une pièce manifeste pour traverser les saisons.',
    priceUSD: 220,
    oldPriceUSD: 275,
    category: 'mode',
    subcategory: 'Vestes & Manteaux',
    tags: ['hiver', 'premium'],
    status: 'active',
    stock: 8,
    rating: 4.7,
    reviewCount: 34,
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Camel', hex: '#C19A6B' },
      { name: 'Brun', hex: '#5C4033' },
    ],
    images: [u('photo-1539109136881-3be0616acf4b'), u('photo-1544022613-e87ca75a784a')],
    badge: 'sale',
  },
  {
    id: 'p-005',
    slug: 'lunettes-rondes-acetate',
    name: 'Lunettes Rondes Acétate',
    shortDescription: 'Acétate écaille, verres anti-reflet',
    description:
      "Lunettes optiques rondes en acétate italien de couleur écaille. Verres traités anti-reflet, charnières renforcées. Un classique réinterprété pour l'esprit ILU.",
    priceUSD: 38,
    category: 'mode',
    subcategory: 'Accessoires',
    tags: ['accessoire', 'unisexe'],
    status: 'active',
    stock: 30,
    rating: 4.5,
    reviewCount: 67,
    images: [u('photo-1574258495973-f010dfbb5371'), u('photo-1577803645773-f96470509666')],
  },
  {
    id: 'p-006',
    slug: 'sweat-oversize-creme',
    name: 'Sweat Oversize Crème',
    shortDescription: 'Molleton lourd 480g',
    description:
      'Sweat oversize en molleton lourd 480g coton bio. Coupe boxy, manches kimono, bord-côtes épais. Le confort élevé au rang de luxe quotidien.',
    priceUSD: 65,
    category: 'mode',
    subcategory: 'Vêtements',
    tags: ['coton bio', 'oversize'],
    status: 'featured',
    stock: 18,
    rating: 4.7,
    reviewCount: 112,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Crème', hex: '#FBF7F2' },
      { name: 'Beige', hex: '#E8DDD0' },
      { name: 'Noir', hex: '#1C1410' },
    ],
    images: [u('photo-1556821840-3a63f95609a7'), u('photo-1620799140408-edc6dcb6d633')],
    badge: 'new',
  },
  {
    id: 'p-007',
    slug: 'robe-fluide-terra',
    name: 'Robe Fluide Terracotta',
    shortDescription: 'Viscose lyocell, mi-longue',
    description:
      "Robe mi-longue en viscose lyocell tombante. Encolure en V, manches courtes, ceinture à nouer. Une coupe flatteuse qui capte la lumière comme un éclat d'argile.",
    priceUSD: 78,
    category: 'mode',
    subcategory: 'Vêtements',
    tags: ['femme', 'été'],
    status: 'active',
    stock: 14,
    rating: 4.8,
    reviewCount: 91,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Terracotta', hex: '#C8573A' },
      { name: 'Olive', hex: '#6B6B3A' },
    ],
    images: [u('photo-1572804013309-59a88b7e92f1'), u('photo-1612722432474-b971cdcea546')],
  },
  {
    id: 'p-008',
    slug: 'ceinture-cuir-tresse',
    name: 'Ceinture Cuir Tressé',
    shortDescription: 'Cuir tressé main, boucle laiton',
    description:
      "Ceinture en cuir tressé à la main par nos artisans. Boucle en laiton vieilli, longueur ajustable. Un détail qui transforme n'importe quelle tenue.",
    priceUSD: 32,
    category: 'mode',
    subcategory: 'Accessoires',
    tags: ['artisanal', 'cuir'],
    status: 'active',
    stock: 22,
    rating: 4.6,
    reviewCount: 43,
    sizes: ['80', '85', '90', '95', '100'],
    colors: [
      { name: 'Cognac', hex: '#9B5A28' },
      { name: 'Noir', hex: '#1C1410' },
    ],
    images: [u('photo-1624222247344-550fb60583dc'), u('photo-1556905055-8f358a7a47b2')],
  },
  // ─── HIGH-TECH ───
  {
    id: 'p-009',
    slug: 'smartphone-aurora-pro',
    name: 'Aurora Pro 256GB',
    shortDescription: '6.7" OLED 120Hz, triple capteur',
    description:
      "Smartphone Aurora Pro. Écran OLED 6.7 pouces 120Hz, processeur dernière génération, triple capteur photo 50MP. 256GB de stockage, charge rapide 65W. L'outil tech qui ne sacrifie ni la performance ni l'élégance.",
    priceUSD: 699,
    oldPriceUSD: 799,
    category: 'telephones',
    subcategory: 'Smartphones',
    tags: ['premium', 'oled'],
    status: 'featured',
    stock: 9,
    rating: 4.7,
    reviewCount: 203,
    colors: [
      { name: 'Titanium', hex: '#8A8580' },
      { name: 'Onyx', hex: '#1C1410' },
      { name: 'Sable', hex: '#D4C4B0' },
    ],
    images: [u('photo-1511707171634-5f897ff02aa9'), u('photo-1592750475338-74b7b21085ab')],
    badge: 'sale',
  },
  {
    id: 'p-010',
    slug: 'laptop-craft-14',
    name: 'Craft Laptop 14"',
    shortDescription: 'M3, 16GB RAM, 512GB SSD',
    description:
      "Ultrabook 14 pouces ultra-fin. Puce M3, 16GB de mémoire unifiée, SSD 512GB. Écran Liquid Retina, autonomie 18h. Pour ceux qui font du laptop un outil d'expression.",
    priceUSD: 1299,
    category: 'ordinateurs',
    subcategory: 'Ultrabooks',
    tags: ['pro', 'premium'],
    status: 'featured',
    stock: 5,
    rating: 4.9,
    reviewCount: 78,
    colors: [
      { name: 'Argent', hex: '#C0BFBC' },
      { name: 'Minuit', hex: '#1C2333' },
    ],
    images: [u('photo-1496181133206-80ce9b88a853'), u('photo-1517336714731-489689fd1ca8')],
    badge: 'hot',
  },
  {
    id: 'p-011',
    slug: 'tablette-canvas-11',
    name: 'Canvas Tablet 11"',
    shortDescription: '128GB Wi-Fi + stylet inclus',
    description:
      'Tablette 11 pouces avec stylet ILU inclus. 128GB, Wi-Fi 6, écran Liquid Retina 120Hz. Conçue pour dessiner, lire, créer — sans compromis.',
    priceUSD: 549,
    category: 'tablettes',
    subcategory: 'Tablettes standard',
    tags: ['créatif', 'stylet'],
    status: 'active',
    stock: 11,
    rating: 4.6,
    reviewCount: 56,
    colors: [
      { name: 'Argent', hex: '#C0BFBC' },
      { name: 'Gris sidéral', hex: '#5C5C5C' },
    ],
    images: [u('photo-1561154464-82e9adf32764'), u('photo-1542751110-97427bbecf20')],
  },
  {
    id: 'p-012',
    slug: 'casque-audio-noir',
    name: 'Casque Audio Sans-Fil',
    shortDescription: 'Réduction active, 40h autonomie',
    description:
      'Casque audio circum-aural sans-fil. Réduction de bruit active, 40h d\'autonomie, charge rapide USB-C. Cuir vegan et acier brossé.',
    priceUSD: 189,
    oldPriceUSD: 229,
    category: 'telephones',
    subcategory: 'Accessoires téléphonie',
    tags: ['audio', 'sans-fil'],
    status: 'active',
    stock: 17,
    rating: 4.7,
    reviewCount: 134,
    colors: [
      { name: 'Noir', hex: '#1C1410' },
      { name: 'Crème', hex: '#FBF7F2' },
    ],
    images: [u('photo-1583394838336-acd977736f90'), u('photo-1545127398-14699f92334b')],
    badge: 'sale',
  },
  {
    id: 'p-013',
    slug: 'chemise-lin-ivoire',
    name: 'Chemise Lin Ivoire',
    shortDescription: 'Lin européen, coupe droite',
    description:
      'Chemise en lin européen tissé serré. Coupe droite, col boutonné, manches ajustables. La pièce qui traverse les étés sans s\'essouffler.',
    priceUSD: 72,
    category: 'mode',
    subcategory: 'Vêtements',
    tags: ['lin', 'été'],
    status: 'active',
    stock: 20,
    rating: 4.6,
    reviewCount: 47,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Ivoire', hex: '#F5EFE6' },
      { name: 'Terracotta', hex: '#C8573A' },
      { name: 'Sauge', hex: '#9CAE9A' },
    ],
    images: [u('photo-1602810318383-e386cc2a3ccf'), u('photo-1620799140408-edc6dcb6d633')],
  },
  {
    id: 'p-014',
    slug: 'bottines-cuir-cognac',
    name: 'Bottines Cuir Cognac',
    shortDescription: 'Cuir tanné, semelle Goodyear',
    description:
      'Bottines à lacets en cuir tanné végétal cognac. Cousu Goodyear, semelle cuir et caoutchouc. Une chaussure qui se ressemelle et accompagne une vie entière.',
    priceUSD: 195,
    category: 'mode',
    subcategory: 'Chaussures',
    tags: ['cuir', 'artisanal'],
    status: 'active',
    stock: 7,
    rating: 4.9,
    reviewCount: 38,
    sizes: ['40', '41', '42', '43', '44', '45'],
    colors: [
      { name: 'Cognac', hex: '#9B5A28' },
      { name: 'Noir', hex: '#1C1410' },
    ],
    images: [u('photo-1543163521-1bf539c55dd2'), u('photo-1605812860427-4024433a70fd')],
  },
  {
    id: 'p-015',
    slug: 'montre-mecanique-or',
    name: 'Montre Mécanique 38mm',
    shortDescription: 'Mouvement automatique, bracelet cuir',
    description:
      "Montre 38mm mouvement mécanique automatique. Boîtier acier finition champagne, cadran ivoire, bracelet cuir cognac. L'élégance d'un objet qui se remonte sans pile.",
    priceUSD: 285,
    category: 'mode',
    subcategory: 'Accessoires',
    tags: ['horlogerie', 'premium'],
    status: 'featured',
    stock: 4,
    rating: 4.8,
    reviewCount: 29,
    colors: [
      { name: 'Champagne', hex: '#D4A84B' },
      { name: 'Argent', hex: '#C0BFBC' },
    ],
    images: [u('photo-1524592094714-0f0654e20314'), u('photo-1547996160-81dfa63595aa')],
    badge: 'featured',
  },
  {
    id: 'p-016',
    slug: 'laptop-stand-bois',
    name: 'Stand Laptop Bois Massif',
    shortDescription: 'Chêne huilé, ergonomique',
    description:
      'Support laptop en chêne massif huilé. Inclinaison ergonomique 15°, ventilation naturelle, patins anti-rayures. Une pièce qui transforme le bureau.',
    priceUSD: 64,
    category: 'ordinateurs',
    subcategory: 'Bureautique',
    tags: ['accessoire', 'bois'],
    status: 'active',
    stock: 15,
    rating: 4.5,
    reviewCount: 22,
    images: [u('photo-1593642632559-0c6d3fc62b89'), u('photo-1611174340026-8eddfbbed26b')],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter((p) => p.status === 'featured');
}

export function getRelatedProducts(product: Product, count = 4): Product[] {
  return PRODUCTS.filter(
    (p) => p.id !== product.id && p.category === product.category,
  ).slice(0, count);
}

export const CATEGORIES = [
  { slug: 'mode', label: 'Mode', count: PRODUCTS.filter((p) => p.category === 'mode').length },
  {
    slug: 'telephones',
    label: 'Téléphones',
    count: PRODUCTS.filter((p) => p.category === 'telephones').length,
  },
  {
    slug: 'ordinateurs',
    label: 'Ordinateurs',
    count: PRODUCTS.filter((p) => p.category === 'ordinateurs').length,
  },
  {
    slug: 'tablettes',
    label: 'Tablettes',
    count: PRODUCTS.filter((p) => p.category === 'tablettes').length,
  },
];
